// <auto-generated />
using System;
using HogarGestor.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HogarGestor.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220831155944_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HogarGestor.App.Dominio.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Registro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.PatronesCrecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("Medicion")
                        .HasColumnType("int");

                    b.Property<float?>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("PatronesCrecimientoJoven");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocumentoTipo")
                        .HasColumnType("int");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.SugerenciaCuidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("SugerenciasCuidado");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Familiar", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Persona");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Familiar");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Joven", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Persona");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamiliarDesignadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HistoriaJovenId")
                        .HasColumnType("int");

                    b.Property<float?>("Latitud")
                        .HasColumnType("real");

                    b.Property<int?>("NutricionistaId")
                        .HasColumnType("int");

                    b.Property<int?>("PediatraId")
                        .HasColumnType("int");

                    b.Property<float?>("longitud")
                        .HasColumnType("real");

                    b.HasIndex("FamiliarDesignadoId");

                    b.HasIndex("HistoriaJovenId");

                    b.HasIndex("NutricionistaId");

                    b.HasIndex("PediatraId");

                    b.HasDiscriminator().HasValue("Joven");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Medico", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Persona");

                    b.Property<int>("EspecialidadMedica")
                        .HasColumnType("int");

                    b.Property<string>("Rethus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarjetaProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Medico");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.PatronesCrecimiento", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Historia", null)
                        .WithMany("PatronCrecimiento")
                        .HasForeignKey("HistoriaId");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.SugerenciaCuidado", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Historia", null)
                        .WithMany("SugerenciasCuidado")
                        .HasForeignKey("HistoriaId");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Joven", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Familiar", "FamiliarDesignado")
                        .WithMany()
                        .HasForeignKey("FamiliarDesignadoId");

                    b.HasOne("HogarGestor.App.Dominio.Historia", "HistoriaJoven")
                        .WithMany()
                        .HasForeignKey("HistoriaJovenId");

                    b.HasOne("HogarGestor.App.Dominio.Medico", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("NutricionistaId");

                    b.HasOne("HogarGestor.App.Dominio.Medico", "Pediatra")
                        .WithMany()
                        .HasForeignKey("PediatraId");

                    b.Navigation("FamiliarDesignado");

                    b.Navigation("HistoriaJoven");

                    b.Navigation("Nutricionista");

                    b.Navigation("Pediatra");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Historia", b =>
                {
                    b.Navigation("PatronCrecimiento");

                    b.Navigation("SugerenciasCuidado");
                });
#pragma warning restore 612, 618
        }
    }
}
