// <auto-generated />
using System;
using HogarGestor.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HogarGestor.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220831194659_Jovenes")]
    partial class Jovenes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HogarGestor.App.Dominio.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Diagnostico")
                        .HasColumnType("int");

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JovenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JovenId");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.PatronesCrecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("JovenId")
                        .HasColumnType("int");

                    b.Property<int>("Medicion")
                        .HasColumnType("int");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("JovenId");

                    b.ToTable("PatronesCrecimiento");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.SugerenciaCuidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("HistoriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("Sugerencias");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumentos");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Familiar", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Persona");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Familiar");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Joven", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Persona");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamiliarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Latitud")
                        .HasColumnType("real");

                    b.Property<float?>("Longitud")
                        .HasColumnType("real");

                    b.Property<int?>("NutricionistaId")
                        .HasColumnType("int");

                    b.Property<int?>("PediatraId")
                        .HasColumnType("int");

                    b.HasIndex("FamiliarId");

                    b.HasIndex("NutricionistaId");

                    b.HasIndex("PediatraId");

                    b.HasDiscriminator().HasValue("Joven");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Medico", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Persona");

                    b.Property<int?>("Especialidad")
                        .HasColumnType("int");

                    b.Property<string>("Rethus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarjetaProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Medico");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Historia", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Joven", null)
                        .WithMany("HistoriaJoven")
                        .HasForeignKey("JovenId");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.PatronesCrecimiento", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Joven", null)
                        .WithMany("PatronesCrecimientoJoven")
                        .HasForeignKey("JovenId");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Persona", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Genero", "Genero")
                        .WithMany("Persona")
                        .HasForeignKey("GeneroId");

                    b.HasOne("HogarGestor.App.Dominio.TipoDocumento", "TipoDocumento")
                        .WithMany("Persona")
                        .HasForeignKey("TipoDocumentoId");

                    b.Navigation("Genero");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.SugerenciaCuidado", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Historia", "Historia")
                        .WithMany("SugerenciaCuidado")
                        .HasForeignKey("HistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historia");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Joven", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Familiar", "Familiar")
                        .WithMany()
                        .HasForeignKey("FamiliarId");

                    b.HasOne("HogarGestor.App.Dominio.Medico", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("NutricionistaId");

                    b.HasOne("HogarGestor.App.Dominio.Medico", "Pediatra")
                        .WithMany()
                        .HasForeignKey("PediatraId");

                    b.Navigation("Familiar");

                    b.Navigation("Nutricionista");

                    b.Navigation("Pediatra");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Genero", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Historia", b =>
                {
                    b.Navigation("SugerenciaCuidado");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.TipoDocumento", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Joven", b =>
                {
                    b.Navigation("HistoriaJoven");

                    b.Navigation("PatronesCrecimientoJoven");
                });
#pragma warning restore 612, 618
        }
    }
}
